//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJack {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DealerEmoji {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DealerEmoji() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BlackJack.DealerEmoji", typeof(DealerEmoji).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string StartFace {
            get {
                return ResourceManager.GetString("StartFace", resourceCulture);
            }
        }
        
        internal static string AngryFace {
            get {
                return ResourceManager.GetString("AngryFace", resourceCulture);
            }
        }
        
        internal static string LooseFace {
            get {
                return ResourceManager.GetString("LooseFace", resourceCulture);
            }
        }
        
        internal static string HappyFace {
            get {
                return ResourceManager.GetString("HappyFace", resourceCulture);
            }
        }
        
        internal static string WinFace {
            get {
                return ResourceManager.GetString("WinFace", resourceCulture);
            }
        }
        
        internal static string DealingFace {
            get {
                return ResourceManager.GetString("DealingFace", resourceCulture);
            }
        }
        
        internal static string DislikeFace {
            get {
                return ResourceManager.GetString("DislikeFace", resourceCulture);
            }
        }
        
        internal static string GoFace {
            get {
                return ResourceManager.GetString("GoFace", resourceCulture);
            }
        }
        
        internal static string WhosWonFace {
            get {
                return ResourceManager.GetString("WhosWonFace", resourceCulture);
            }
        }
        
        internal static string PlayerBustFace {
            get {
                return ResourceManager.GetString("PlayerBustFace", resourceCulture);
            }
        }
        
        internal static string NextRoundFace {
            get {
                return ResourceManager.GetString("NextRoundFace", resourceCulture);
            }
        }
        
        internal static string BothBustFace {
            get {
                return ResourceManager.GetString("BothBustFace", resourceCulture);
            }
        }
    }
}
