#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BlackJack.Resource", IsApplication=true)]

namespace BlackJack
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AppLogo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonClicked = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ButtonClickedState = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ButtonDefault = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int CardBack = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int CardBackground = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Clubs = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Diamonds = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Hearts = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Logo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Spades = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int SplashScreen = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int BottomRightChar = 2131230723;
			
			// aapt resource value: 0x7f08001d
			public const int ButtonGame = 2131230749;
			
			// aapt resource value: 0x7f08001c
			public const int ButtonHit = 2131230748;
			
			// aapt resource value: 0x7f080007
			public const int ButtonHome = 2131230727;
			
			// aapt resource value: 0x7f08001b
			public const int ButtonStick = 2131230747;
			
			// aapt resource value: 0x7f080012
			public const int ConvoText = 2131230738;
			
			// aapt resource value: 0x7f08000a
			public const int DealerGameScore = 2131230730;
			
			// aapt resource value: 0x7f080011
			public const int DealersFifthCard = 2131230737;
			
			// aapt resource value: 0x7f08000d
			public const int DealersFirstCard = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int DealersFourthCard = 2131230736;
			
			// aapt resource value: 0x7f08000c
			public const int DealersHand = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int DealersHandText = 2131230731;
			
			// aapt resource value: 0x7f08000e
			public const int DealersSecondCard = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int DealersThirdCard = 2131230735;
			
			// aapt resource value: 0x7f080000
			public const int LayoutCard = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int PlayAgain = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int PlayerGameScore = 2131230729;
			
			// aapt resource value: 0x7f080019
			public const int PlayersFifthCard = 2131230745;
			
			// aapt resource value: 0x7f080015
			public const int PlayersFirstCard = 2131230741;
			
			// aapt resource value: 0x7f080018
			public const int PlayersFourthCard = 2131230744;
			
			// aapt resource value: 0x7f080014
			public const int PlayersHand = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int PlayersHandText = 2131230739;
			
			// aapt resource value: 0x7f080016
			public const int PlayersSecondCard = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int PlayersThirdCard = 2131230743;
			
			// aapt resource value: 0x7f080008
			public const int ScoreBar = 2131230728;
			
			// aapt resource value: 0x7f080002
			public const int SuitImage = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int TextGamePoints = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int TopLeftChar = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int WinnerText = 2131230725;
			
			// aapt resource value: 0x7f08001a
			public const int bottom_panel = 2131230746;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CardTemplate = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int EndGame = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Game = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int ShuffleSound = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int MyTheme = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int MyTheme_Base = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int MyTheme_Splash = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
