#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BlackJack.Resource", IsApplication=true)]

namespace BlackJack
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AppLogo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonClicked = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ButtonClickedState = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ButtonDefault = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int CardBack = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int CardBackground = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Clubs = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Diamonds = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Hearts = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Logo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Spades = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int BottomRightChar = 2131099651;
			
			// aapt resource value: 0x7f06001c
			public const int ButtonGame = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int ButtonHit = 2131099675;
			
			// aapt resource value: 0x7f060006
			public const int ButtonHome = 2131099654;
			
			// aapt resource value: 0x7f06001a
			public const int ButtonStick = 2131099674;
			
			// aapt resource value: 0x7f060011
			public const int ConvoText = 2131099665;
			
			// aapt resource value: 0x7f060009
			public const int DealerGameScore = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int DealersFifthCard = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public const int DealersFirstCard = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int DealersFourthCard = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int DealersHand = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int DealersHandText = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int DealersSecondCard = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int DealersThirdCard = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int LayoutCard = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int PlayAgain = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int PlayerGameScore = 2131099656;
			
			// aapt resource value: 0x7f060018
			public const int PlayersFifthCard = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int PlayersFirstCard = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int PlayersFourthCard = 2131099671;
			
			// aapt resource value: 0x7f060013
			public const int PlayersHand = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int PlayersHandText = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int PlayersSecondCard = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int PlayersThirdCard = 2131099670;
			
			// aapt resource value: 0x7f060007
			public const int ScoreBar = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int SuitImage = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int TopLeftChar = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int WinnerText = 2131099652;
			
			// aapt resource value: 0x7f060019
			public const int bottom_panel = 2131099673;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CardTemplate = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int EndGame = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Game = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
